external-secrets:
  replicaCount: 2

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

  webhook:
    replicaCount: 2
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi

  certController:
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
