version: 2

project_name: cluster-bootstrap-cli

before:
  hooks:
    - sh -c 'cd cluster-bootstrap-cli && go mod tidy'

builds:
  - main: ./main.go
    dir: cluster-bootstrap-cli
    binary: cluster-bootstrap-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - apps/**/*
      - components/**/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
