version: 2

project_name: cluster-bootstrap-cli

before:
  hooks:
    - sh -c 'cd cluster-bootstrap-cli && go mod tidy'

builds:
  - main: ./main.go
    dir: cluster-bootstrap-cli
    binary: cluster-bootstrap-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/user-cube/cluster-bootstrap/cluster-bootstrap-cli/cmd.Version={{.Version}}
      - -X github.com/user-cube/cluster-bootstrap/cluster-bootstrap-cli/cmd.Commit={{.FullCommit}}
      - -X github.com/user-cube/cluster-bootstrap/cluster-bootstrap-cli/cmd.Date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - apps/**/*
      - components/**/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

dockers:
  - image_templates:
      - "ghcr.io/user-cube/cluster-bootstrap-cli:{{.Version}}-amd64"
      - "ghcr.io/user-cube/cluster-bootstrap-cli:latest-amd64"
    use: docker
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64

  - image_templates:
      - "ghcr.io/user-cube/cluster-bootstrap-cli:{{.Version}}-arm64"
      - "ghcr.io/user-cube/cluster-bootstrap-cli:latest-arm64"
    use: docker
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/user-cube/cluster-bootstrap-cli:{{.Version}}"
    image_templates:
      - "ghcr.io/user-cube/cluster-bootstrap-cli:{{.Version}}-amd64"
      - "ghcr.io/user-cube/cluster-bootstrap-cli:{{.Version}}-arm64"
  - name_template: "ghcr.io/user-cube/cluster-bootstrap-cli:latest"
    image_templates:
      - "ghcr.io/user-cube/cluster-bootstrap-cli:latest-amd64"
      - "ghcr.io/user-cube/cluster-bootstrap-cli:latest-arm64"
