project_name: cluster-bootstrap

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    dir: cli
    binary: cluster-bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
