version: "3"

includes:
  cli:
    taskfile: cluster-bootstrap-cli/Taskfile.yml
    dir: cluster-bootstrap-cli

tasks:
  build:
    desc: Build the CLI binary
    cmds:
      - task: cli:build

  install:
    desc: Install the CLI globally as 'cluster-bootstrap-cli'
    dir: cluster-bootstrap-cli
    cmds:
      - go install
      - |
        echo "✅ Installed as 'cluster-bootstrap-cli' in $(go env GOPATH)/bin"
        echo "   Run: cluster-bootstrap-cli --help"

  test:
    desc: Run Go tests with coverage
    dir: cluster-bootstrap-cli
    cmds:
      - go test -cover ./...

  lint:
    desc: Run golangci-lint on the CLI
    dir: cluster-bootstrap-cli
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format Go source files
    cmds:
      - task: cli:fmt

  vet:
    desc: Run Go vet
    cmds:
      - task: cli:vet

  helm-lint:
    desc: Lint all Helm charts
    cmds:
      - |
        helm lint apps/
        for chart in components/*/; do
          if grep -q "^dependencies:" "$chart/Chart.yaml"; then
            helm dependency build "$chart"
          fi
          values_args=""
          if [ -f "$chart/values/base.yaml" ]; then
            values_args="-f $chart/values/base.yaml"
          fi
          helm lint "$chart" $values_args
        done

  helm-template:
    desc: Render Helm templates for a given environment
    vars:
      ENV: '{{.ENV | default "dev"}}'
    cmds:
      - helm template apps/ -f apps/values/{{.ENV}}.yaml

  docs-serve:
    desc: Serve MkDocs documentation locally
    cmds:
      - mkdocs serve
