vault:
  injector:
    enabled: false
  ui:
    enabled: true

vaultConfig:
  enabled: true
  role: external-secrets
  serviceAccount: external-secrets
  serviceAccountNamespace: external-secrets
  policyName: external-secrets
  policyPath: "secret/*"
