{{- if .Values.argocdRepoSecret.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repo-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.targetRevision }}
    path: components/argocd-repo-secret
    helm:
      valueFiles:
        - values/base.yaml
        - values/{{ .Values.environment }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
