apiVersion: v2
name: external-secrets
description: External Secrets Operator managed by App of Apps
version: 1.0.0
type: application
dependencies:
  - name: external-secrets
    version: 0.20.4
    repository: https://charts.external-secrets.io
