provider: vault

vault:
  kvPath: secret
  kvVersion: "v2"
  authType: kubernetes
  kubernetesRole: external-secrets
  kubernetesMountPath: kubernetes
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets

aws:
  region: eu-west-1
  authSecret: aws-credentials

externalSecret:
  refreshInterval: 1h
  vaultSecretPath: argocd/repo-ssh-key
  awsSecretName: argocd/repo-ssh-key
