apiVersion: v2
name: argocd
description: ArgoCD component managed by App of Apps
version: 1.0.0
type: application
dependencies:
  - name: argo-cd
    version: 9.4.3
    repository: https://argoproj.github.io/argo-helm
